#!/usr/bin/env sh
# mutate.sh: find out which shell checks actually catch a fault.
#
# The suite protects a list of promises. Reading it tells you what it means to
# catch. Only breaking something tells you what it does catch. Each mutation
# here is one reversible edit that breaks one promise. The script applies it to
# a throwaway clone, runs the checks, and records which ones noticed.
#
# Two lists come out. Mutations nothing caught are holes. Checks that caught
# nothing are candidates for removal.
#
# Usage:
#   ./mutate.sh                 every mutation
#   ./mutate.sh manifest-drop   one or more by name
#   ./mutate.sh --list          the names and what each one breaks
#
# The clone takes committed history only, so uncommitted work in your tree is
# not audited. Commit a fix before asking whether it closes a hole.
#
# For anyone extending this: every mutation asserts that the text it expects is
# there before changing it, and the runner refuses a mutation that leaves the
# tree unchanged. A mutation that quietly matches nothing reports a hole that
# does not exist, which is worse than no result at all. Do not edit this file
# while a run is in progress either, because the shell reads a script as it
# goes and the edit will derail it part way through.

set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
WORK=${MUTATE_WORK:-${TMPDIR:-/tmp}/abk-mutate-$$}
REPORT="$WORK/report.tsv"

# validate-kit.sh runs every one of the other checks itself, at lines 870 to
# 946, so it is an aggregate rather than an independent opinion. It runs here
# because it also carries checks of its own, on links, stale vocabulary and
# adapter freshness. When reading the report, a catch by validate-kit alone
# means only its own direct checks noticed.
DEFAULT_CHECKS="release-builder starter-rehearsal agent-plugin session-start validate-kit"
PUBLISH_CHECKS="release-builder release-publication validate-kit"
MODE_CHECKS="validate-kit fake-github"

MUTATIONS="manifest-drop
manifest-drop-unpaired
humanizer-leak
review-issues-leak
bootstrap-overwrite
bootstrap-escape
maintainer-name-leak
adapter-stale
skill-missing
skill-duplicate
publish-writes-a-tree
gate-widened
discipline-user-invocable
hook-speaks-in-source
hook-speaks-in-cadence
broken-link
stale-term
agent-manifest-extra-field
release-nondeterministic
runnable-bit-lost"

# The checks that guard a rule written as prose are found the way
# validate-kit.sh finds them, by the helper they source, so this list cannot
# fall behind the repository.
RULE_SHAPE_CHECKS=$(grep -l 'lib/rule-shape\.sh' "$ROOT"/.agents/tests/*.sh 2>/dev/null \
  | while IFS= read -r rs_file; do basename -- "$rs_file" .sh; done | sort)
for rs_name in $RULE_SHAPE_CHECKS; do
  MUTATIONS="$MUTATIONS
rule-$rs_name"
done

describe() {
  case "$1" in
    manifest-drop) echo "a document named in both manifests is dropped from the release allowlist" ;;
    manifest-drop-unpaired) echo "a file named only in the release allowlist is dropped, with no second manifest to cross-check it" ;;
    humanizer-leak) echo "the maintainer's writing skill is put back beside the fourteen and allowed into the release" ;;
    review-issues-leak) echo "the maintainer's issue review, the skill nobody wrote a check for by name, is put beside the fourteen and allowed into the release" ;;
    bootstrap-overwrite) echo "project bootstrap overwrites a file the project already had" ;;
    bootstrap-escape) echo "project bootstrap follows a link and writes outside the project" ;;
    maintainer-name-leak) echo "the private source repository is named in the public README" ;;
    adapter-stale) echo "a skill changes without its adapters being regenerated" ;;
    skill-missing) echo "one skill folder disappears, leaving ten" ;;
    skill-duplicate) echo "one skill is replaced by a copy of another, leaving the wrong fourteen" ;;
    publish-writes-a-tree) echo "a workflow gains the power to replace this repository's tree" ;;
    gate-widened) echo "a workflow gate names a repository the kit no longer lives in" ;;
    discipline-user-invocable) echo "a background skill loses the setting that keeps it out of the person's hands" ;;
    hook-speaks-in-source) echo "the session hook speaks inside the kit's own source" ;;
    hook-speaks-in-cadence) echo "the session hook speaks before a visit is overdue" ;;
    broken-link) echo "a local Markdown link points at nothing" ;;
    stale-term) echo "retired vocabulary reappears in a project-facing document" ;;
    agent-manifest-extra-field) echo "the agent plugin manifest carries a field the standard omits" ;;
    release-nondeterministic) echo "an untracked file inside an approved folder enters the release" ;;
    runnable-bit-lost) echo "a script that is started by path loses its saved runnable bit" ;;
    rule-*) echo "a rule ${1#rule-} guards is quietly deleted from the document it lives in" ;;
    *) echo "unknown mutation" ;;
  esac
}

checks_for() {
  case "$1" in
    publish-writes-a-tree) echo "$PUBLISH_CHECKS" ;;
    gate-widened) echo "$MODE_CHECKS" ;;
    runnable-bit-lost) echo "$MODE_CHECKS" ;;
    discipline-user-invocable) echo "validate-kit" ;;
    rule-*) echo "${1#rule-} validate-kit" ;;
    *) echo "$DEFAULT_CHECKS" ;;
  esac
}

# edit <file> <python source>
# Run one small Python edit against one file. Having a single helper means no
# mutation needs its own heredoc, which is what made an earlier version of this
# script so easy to corrupt while patching it.
edit() {
  [ -f "$1" ] || { echo "missing file: $1" >&2; return 1; }
  MUTATE_TARGET="$1" python3 -c "$2"
}

# apply <name> <tree>
# One plausible mistake each: a forgotten manifest line, a guard relaxed to get
# something passing. Not sabotage.
apply() {
  name=$1
  tree=$2
  case "$name" in
    manifest-drop)
      grep -v '^docs/SOURCES\.md|' "$tree/release-manifest.txt" > "$tree/rm.tmp"
      mv "$tree/rm.tmp" "$tree/release-manifest.txt"
      ;;
    manifest-drop-unpaired)
      grep -v '^CONTRIBUTING\.md|' "$tree/release-manifest.txt" > "$tree/rm.tmp"
      mv "$tree/rm.tmp" "$tree/release-manifest.txt"
      ;;
    humanizer-leak)
      # The writing skill is kept out of a user's project by living outside
      # every folder an installer reads, so the mistake to rehearse is moving it
      # back into one. A project would then be offered a fifteenth skill.
      [ -d "$tree/.agents/maintainer-skills/humanizer" ] || return 1
      cp -R "$tree/.agents/maintainer-skills/humanizer" \
        "$tree/.agents/skills/humanizer"
      printf '%s\n' '.agents/skills/humanizer/|' >> "$tree/release-manifest.txt"
      ;;
    review-issues-leak)
      # The same mistake with the other maintainer skill. The three checks that
      # guard the boundary once named humanizer and nothing else, so this is
      # the leak they would have missed. It exists so that the checks are
      # proved to read the folder rather than a name.
      [ -d "$tree/.agents/maintainer-skills/review-issues" ] || return 1
      cp -R "$tree/.agents/maintainer-skills/review-issues" \
        "$tree/.agents/skills/review-issues"
      printf '%s\n' '.agents/skills/review-issues/|' >> "$tree/release-manifest.txt"
      printf '%s\n' '.agents/skills/review-issues|agent-plugin/skills/review-issues' >> "$tree/release-manifest.txt"
      ;;
    bootstrap-overwrite)
      edit "$tree/.agents/skills/setup-ai-build-kit/scripts/bootstrap-project.sh" '
import os
p = os.environ["MUTATE_TARGET"]
t = open(p).read()
old = "if [ -e \"$destination_file\" ] || [ -L \"$destination_file\" ]; then"
assert old in t, "keep-existing guard not found"
open(p, "w").write(t.replace(old, "if [ -L \"$destination_file\" ]; then", 1))
'
      ;;
    bootstrap-escape)
      edit "$tree/.agents/skills/setup-ai-build-kit/scripts/bootstrap-project.sh" '
import os
p = os.environ["MUTATE_TARGET"]
t = open(p).read()
assert "-L " in t, "no symlink guard to break"
open(p, "w").write(t.replace("-L ", "-Z "))
'
      ;;
    maintainer-name-leak)
      printf '\n%s\n' 'Built from ai-build-kit-maintainer.' >> "$tree/README.md"
      ;;
    adapter-stale)
      edit "$tree/.agents/skills/what-now/SKILL.md" '
import os
p = os.environ["MUTATE_TARGET"]
lines = open(p).read().split("\n")
for i, line in enumerate(lines):
    if line.startswith("description:"):
        lines[i] = "description: Work out what to do next, and say so plainly."
        break
else:
    raise SystemExit("no description line")
open(p, "w").write("\n".join(lines))
'
      ;;
    skill-missing)
      rm -R "$tree/.agents/skills/sync"
      ;;
    skill-duplicate)
      rm -R "$tree/.agents/skills/sync"
      cp -R "$tree/.agents/skills/ship" "$tree/.agents/skills/sync"
      ;;
    publish-writes-a-tree)
      # The removed starter publisher made an assembled tree the exact contents
      # of another repository's main branch. With one repository that same act
      # would replace the source with a packaged release, so the mistake worth
      # rehearsing is a workflow quietly regaining the power to push.
      edit "$tree/.github/workflows/verify-release.yml" '
import os
p = os.environ["MUTATE_TARGET"]
t = open(p).read()
old = "  contents: read"
assert old in t, "no read-only permission block to widen"
t = t.replace(old, "  contents: write", 1)
t += "      - name: Record the verified release\n        run: git push origin HEAD:refs/heads/verified\n"
open(p, "w").write(t)
'
      ;;
    gate-widened)
      # Every gate named two repositories while the move was in progress. Naming
      # one the kit has left lets a job run where nobody is watching, and that is
      # as quiet a fault as a job failing to run where somebody is.
      #
      # The quote character is built rather than typed: this Python is carried
      # inside a single-quoted shell string, so a literal one would end it.
      edit "$tree/.github/workflows/source-checks.yml" '
import os
q = chr(39)
p = os.environ["MUTATE_TARGET"]
t = open(p).read()
old = "github.repository == " + q + "gwpicard/ai-build-kit" + q
assert old in t, "no narrowed gate to widen"
both = q + "[" + chr(34) + "gwpicard/ai-build-kit-maintainer" + chr(34) + ", " + chr(34) + "gwpicard/ai-build-kit" + chr(34) + "]" + q
new = "contains(fromJSON(" + both + "), github.repository)"
open(p, "w").write(t.replace(old, new))
'
      ;;
    discipline-user-invocable)
      # The one trigger setting the kit uses is `user-invocable: false`, and it
      # is what makes a skill a background skill rather than a command. Take
      # it off one and the inventory reads ten commands and three background
      # skills. The adapters are rebuilt so the tree is self-consistent, and
      # the fault has to be caught in the source rather than as adapter drift.
      edit "$tree/.agents/skills/clarify/SKILL.md" '
import os
p = os.environ["MUTATE_TARGET"]
t = open(p).read()
assert "user-invocable: false\n" in t, "clarify carries no background-skill setting to remove"
open(p, "w").write(t.replace("user-invocable: false\n", "", 1))
'
      (cd "$tree" && ./.agents/tools/build-adapters.sh >/dev/null 2>&1) || true
      ;;
    hook-speaks-in-source)
      edit "$tree/.agents/skills/setup-ai-build-kit/templates/foundation/session-start.sh" '
import os
p = os.environ["MUTATE_TARGET"]
t = open(p).read()
assert "release-manifest.txt" in t, "no maintainer-source guard"
open(p, "w").write(t.replace("release-manifest.txt", "release-manifest-NOPE.txt"))
'
      ;;
    hook-speaks-in-cadence)
      edit "$tree/.agents/skills/setup-ai-build-kit/templates/foundation/session-start.sh" '
import os, re
p = os.environ["MUTATE_TARGET"]
t = open(p).read()
assert re.search(r"\b35\b", t), "no cadence value found"
open(p, "w").write(re.sub(r"\b35\b", "1", t, count=1))
'
      ;;
    broken-link)
      printf '\n%s\n' 'See [the missing note](MISSING-NOTE.md).' >> "$tree/docs/PHILOSOPHY.md"
      ;;
    stale-term)
      printf '\n%s\n' 'Answer the six questions before adding anything.' >> "$tree/docs/PHILOSOPHY.md"
      ;;
    agent-manifest-extra-field)
      edit "$tree/agent-plugin/plugin.json" '
import json, os
p = os.environ["MUTATE_TARGET"]
d = json.load(open(p))
assert "displayName" not in d, "field already present"
d["displayName"] = "AI Build Kit"
json.dump(d, open(p, "w"), indent=2)
'
      ;;
    release-nondeterministic)
      # The builder stops consulting Git and copies whatever is on disk, so an
      # untracked working file inside an approved folder reaches the starter.
      # Creating a stray file is not itself a mutation: the promise is that
      # untracked files do not ship, and the runner would stage it anyway.
      edit "$tree/.agents/tools/build-release.sh" '
import os
p = os.environ["MUTATE_TARGET"]
t = open(p).read()
assert "git -C \"$ROOT\" ls-files" in t, "no tracked-file lookup to break"
t = t.replace("git -C \"$ROOT\" ls-files --",
              "(cd \"$ROOT\" && find -L", 1)
open(p, "w").write(t)
'
      printf '%s\n' 'stray working note' > "$tree/docs/STRAY-NOTE.md"
      ;;
    runnable-bit-lost)
      # Not a text edit. The stand-in for the GitHub command line tool is
      # started by path, so losing the bit stops it running at all, and this is
      # the shape that reached main twice without any check noticing.
      target="$tree/.agents/tests/replay/fake-github/gh"
      [ -x "$target" ] || { echo "the stand-in is already not runnable" >&2; return 1; }
      chmod -x "$target"
      ;;
    rule-*)
      # Every check that reads a rule written as prose gets one of these. The
      # check is asked, in the mutated tree, which rules it guards and where
      # they live, then the first one is deleted from the document itself. So
      # this script never keeps its own copy of a sentence that lives somewhere
      # else, and a check written tomorrow is audited from the day it exists.
      #
      # Until now none of that family was exercised at all: the single
      # hand-written rule mutation this replaces was routed to a list of checks
      # that did not include the check built to catch it, so validate-kit caught
      # it alone and thirteen checks were never asked.
      rule_check=${name#rule-}
      RS_LIST=1 sh "$tree/.agents/tests/$rule_check.sh" \
        > "$WORK/$name.rules" 2>/dev/null || true
      [ -s "$WORK/$name.rules" ] || {
        echo "$rule_check listed no rules" >&2
        return 1
      }
      MUTATE_RULES="$WORK/$name.rules" python3 -c '
import os, re
target = None
for line in open(os.environ["MUTATE_RULES"]):
    parts = line.rstrip("\n").split("\t")
    if len(parts) < 2:
        continue
    path, pattern = parts[0], parts[1]
    if not os.path.isfile(path):
        continue
    original = open(path).read()
    # Newline to space and lower are both one character for one character, so a
    # match found in the folded text has the same offsets in the real file.
    folded = original.replace("\n", " ").lower()
    found = re.search(pattern, folded)
    if found and found.end() > found.start():
        target = (path, original, found.start(), found.end())
        break
assert target, "no listed rule could be found in the document it names"
path, original, start, end = target
open(path, "w").write(original[:start] + original[end:])
'
      ;;
    *)
      echo "unknown mutation: $name" >&2
      return 1
      ;;
  esac
}

if [ "${1:-}" = "--list" ]; then
  for name in $MUTATIONS; do
    printf '%-28s %s\n' "$name" "$(describe "$name")"
  done
  exit 0
fi

command -v python3 >/dev/null 2>&1 || { echo "FAIL: python3 is required" >&2; exit 1; }

# A time cap stops a wedged check running forever. timeout is GNU coreutils and
# is not on macOS by default, where Homebrew installs it as gtimeout. Use
# whichever is here. If neither is, run without a cap rather than stopping: a
# check that overruns is a rarer problem than an audit that cannot start, and a
# missing timeout used to fail every check at once and report the suite as
# broken. replay/run.sh resolves it the same way.
if command -v timeout >/dev/null 2>&1; then
  TIMEOUT_CMD=timeout
elif command -v gtimeout >/dev/null 2>&1; then
  TIMEOUT_CMD=gtimeout
else
  TIMEOUT_CMD=
  echo "note: no timeout or gtimeout found, so checks run without a time cap" >&2
fi

wanted=${*:-$MUTATIONS}
mkdir -p "$WORK"
printf 'mutation\tcaught_by\tchecks_run\tdescription\n' > "$REPORT"

run_check() {
  if [ "$2" = "validate-kit" ]; then
    script="$1/.agents/tools/validate-kit.sh"
  else
    script="$1/.agents/tests/$2.sh"
  fi
  if [ -n "$TIMEOUT_CMD" ]; then
    "$TIMEOUT_CMD" 1800 "$script" >"$WORK/$3-$2.log" 2>&1
  else
    "$script" >"$WORK/$3-$2.log" 2>&1
  fi
}

# A clean baseline first. If the suite is not green before anything is broken,
# nothing after this means anything.
echo "Baseline: running the checks against an unmutated clone"
BASE="$WORK/baseline"
git clone --quiet --local --no-hardlinks "$ROOT" "$BASE"
baseline_failures=""
for check in $DEFAULT_CHECKS; do
  run_check "$BASE" "$check" baseline || baseline_failures="$baseline_failures $check"
done
if [ -n "$baseline_failures" ]; then
  echo "FAIL: the suite is not green before any mutation:$baseline_failures" >&2
  echo "Logs are in $WORK" >&2
  exit 1
fi
echo "Baseline is green."
echo

for name in $wanted; do
  checks=$(checks_for "$name")
  tree="$WORK/$name"
  echo "Mutation: $name"
  echo "  breaks: $(describe "$name")"

  git clone --quiet --local --no-hardlinks "$ROOT" "$tree"

  status=applied
  if ! apply "$name" "$tree" >"$WORK/$name-apply.log" 2>&1; then
    status=NOT-APPLIED
  elif [ -z "$(git -C "$tree" status --porcelain)" ]; then
    # A mutation that changes nothing would otherwise be reported as a hole.
    status=NO-CHANGE
  fi

  if [ "$status" != applied ]; then
    echo "  $status: this result would be false, so it is not counted"
    [ "$status" = NOT-APPLIED ] && echo "  see $WORK/$name-apply.log"
    printf '%s\t%s\t%s\t%s\n' "$name" "$status" "$(echo $checks | tr ' ' ',')" \
      "$(describe "$name")" >> "$REPORT"
    echo
    continue
  fi

  # Staged rather than committed, so a newly added file reaches the release
  # builder's tracked-file list without a commit in the way.
  git -C "$tree" add -A >/dev/null 2>&1 || true

  caught=""
  for check in $checks; do
    if run_check "$tree" "$check" "$name"; then
      printf '    %-22s passed\n' "$check"
    else
      printf '    %-22s CAUGHT IT\n' "$check"
      caught="$caught $check"
    fi
  done

  if [ -z "$caught" ]; then
    echo "  NOTHING CAUGHT THIS"
    caught_field="none"
  else
    caught_field=$(echo $caught | tr ' ' ',')
  fi
  printf '%s\t%s\t%s\t%s\n' "$name" "$caught_field" "$(echo $checks | tr ' ' ',')" \
    "$(describe "$name")" >> "$REPORT"
  echo
done

echo "================================================================"
echo "Report: $REPORT"
echo "================================================================"
column -t -s "$(printf '\t')" "$REPORT" 2>/dev/null || cat "$REPORT"
echo
echo "Uncaught mutations are holes in the suite:"
awk -F'\t' 'NR > 1 && $2 == "none" { print "  " $1 "  " $4 }' "$REPORT"
echo
echo "Mutations that proved nothing, because they did not take effect:"
awk -F'\t' 'NR > 1 && ($2 == "NO-CHANGE" || $2 == "NOT-APPLIED") { print "  " $1 }' "$REPORT"
echo
echo "Logs and clones are in $WORK"
