#!/usr/bin/env sh
# A stand-in for df. It prints the POSIX layout of `df -Pk <folder>`.
gb=${FAKE_COMPUTER_DISK_GB:-100}
avail=$((gb * 1024 * 1024))
echo "Filesystem    1024-blocks      Used Available Capacity  Mounted on"
echo "/dev/disk3s5    971350180 400000000 $avail    62%    /System/Volumes/Data"
